<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.controller.gallery' shared service.

return $this->services['oneup_uploader.controller.gallery'] = new \Oneup\UploaderBundle\Controller\DropzoneController($this, ${($_ = isset($this->services['oneup_uploader.storage.gallery']) ? $this->services['oneup_uploader.storage.gallery'] : ($this->services['oneup_uploader.storage.gallery'] = new \Oneup\UploaderBundle\Uploader\Storage\FilesystemStorage(($this->targetDirs[3].'\\app/../web/uploads/gallery')))) && false ?: '_'}, new \Oneup\UploaderBundle\Uploader\ErrorHandler\DropzoneErrorHandler(), ['frontend' => 'dropzone', 'custom_frontend' => ['name' => NULL, 'class' => NULL], 'storage' => ['service' => NULL, 'type' => 'filesystem', 'filesystem' => NULL, 'directory' => ($this->targetDirs[3].'\\app/../web/uploads/gallery'), 'stream_wrapper' => NULL, 'sync_buffer_size' => '100K'], 'route_prefix' => '', 'endpoints' => ['upload' => NULL, 'progress' => NULL, 'cancel' => NULL], 'allowed_mimetypes' => [], 'disallowed_mimetypes' => [], 'error_handler' => NULL, 'max_size' => 9223372036854775807, 'use_orphanage' => false, 'enable_progress' => false, 'enable_cancelation' => false, 'namer' => 'oneup_uploader.namer.uniqid', 'root_folder' => false], 'gallery');
