<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.form.registration' shared service.

return $this->services['app.form.registration'] = new \Eshop\UserBundle\Form\Type\RegistrationType();
