<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUdznuxe\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUdznuxe/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUdznuxe.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUdznuxe\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerUdznuxe\appProdDebugProjectContainer([
    'container.build_hash' => 'Udznuxe',
    'container.build_id' => 'f46cb623',
    'container.build_time' => 1606150092,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUdznuxe');
