<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVa8och9\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVa8och9/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVa8och9.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVa8och9\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerVa8och9\appProdDebugProjectContainer([
    'container.build_hash' => 'Va8och9',
    'container.build_id' => '203b4b00',
    'container.build_time' => 1606155721,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVa8och9');
