<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1qv3hif\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1qv3hif/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/Container1qv3hif.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\Container1qv3hif\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \Container1qv3hif\appProdDebugProjectContainer([
    'container.build_hash' => '1qv3hif',
    'container.build_id' => '308b2a1e',
    'container.build_time' => 1606985118,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1qv3hif');
