<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.templating.helper.oauth' shared service.

$this->services['hwi_oauth.templating.helper.oauth'] = $instance = new \HWI\Bundle\OAuthBundle\Templating\Helper\OAuthHelper(${($_ = isset($this->services['hwi_oauth.security.oauth_utils']) ? $this->services['hwi_oauth.security.oauth_utils'] : $this->load('getHwiOauth_Security_OauthUtilsService.php')) && false ?: '_'});

$instance->setRequest(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});

return $instance;
