<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'skies_barcode.generator' shared service.

return $this->services['skies_barcode.generator'] = new \Skies\QRcodeBundle\Generator\Generator();
