<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'skies_barcode.twig.extension' shared service.

return $this->services['skies_barcode.twig.extension'] = new \Skies\QRcodeBundle\Twig\Extensions\Barcode(${($_ = isset($this->services['skies_barcode.generator']) ? $this->services['skies_barcode.generator'] : ($this->services['skies_barcode.generator'] = new \Skies\QRcodeBundle\Generator\Generator())) && false ?: '_'});
