<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAwhungi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwhungi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAwhungi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAwhungi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAwhungi\appDevDebugProjectContainer([
    'container.build_hash' => 'Awhungi',
    'container.build_id' => '179a2645',
    'container.build_time' => 1606123132,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwhungi');
